### PR TITLE
55856 - Created Admin Page 

### PR DESCRIPTION
**Pull request by gursimar03**
- Created Admin Page
- Added AuthProvider for authentication and route protection
- Update apis method to work with backend

### CODE REVIEW

**Review by Erlinguss — APPROVED** [review]
I have reviewed the code.

**Review by RobertNugent04 — COMMENTED** [review]
Could you add an image of the admin page please.

**Comment by gursimar03** [comment]
@RobertNugent04 The admin page does not have any UI change it was majorly underlying code change, I am still using the same component you made which is on main.

**Comment by RobertNugent04** [comment]
@gursimar03 All the code you wrote looks good to me. Great Work!

**Review by RobertNugent04 — APPROVED** [review]

**Pull request merged**
